development:
  adapter: <%= ENV['REDMINE_DB_ADAPTER'] || 'postgresql' %>
  database: <%= ENV['REDMINE_DB_DATABASE'] || 'postgres' %>
  host: <%= ENV['REDMINE_DB_HOST'] || 'localhost' %>
  port: <%= ENV['REDMINE_DB_PORT'] || '5432' %>
  username: <%= ENV['REDMINE_DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['REDMINE_DB_PASSWORD'] || 'postgres' %>

test:
  adapter: <%= ENV['REDMINE_DB_ADAPTER'] || 'postgresql' %>
  database: <%= ENV['REDMINE_DB_DATABASE'] || 'postgres' %>
  host: <%= ENV['REDMINE_DB_HOST'] || 'localhost' %>
  port: <%= ENV['REDMINE_DB_PORT'] || '5432' %>
  username: <%= ENV['REDMINE_DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['REDMINE_DB_PASSWORD'] || 'postgres' %>

production:
  adapter: <%= ENV['REDMINE_DB_ADAPTER'] || 'postgresql' %>
  database: <%= ENV['REDMINE_DB_DATABASE'] || 'postgres' %>
  host: <%= ENV['REDMINE_DB_HOST'] || 'localhost' %>
  port: <%= ENV['REDMINE_DB_PORT'] || '5432' %>
  username: <%= ENV['REDMINE_DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['REDMINE_DB_PASSWORD'] || 'postgres' %>
